config/routes.rb
Rails.application.routes.draw do

  get 'about' => 'welcome#about'
  root 'welcome#index'
  resources :wikis
  resources :wikis, only: [] do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :users, only: [] do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]

  devise_for :users

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :wikis
  has_many :collaborators, through: :wikis, dependent: :destroy

  after_initialize {self.role ||= :standard}

  enum role: [:standard, :premium, :admin]

  def collaborator_for(wiki)
    collaborators.where(wiki_id: wiki.id).first
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, through: :user, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    current_user.stripe_ID = customer.id

    charge = Stripe::Charge.create(
      customer: current_user.stripe_ID,
      amount: 15_00,
      description: "Blocipedia Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    flash[:notice] = "Thank you! Your account has been upgraded to the premium membership."
    current_user.role = 'premium'
    current_user.save
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      current_user.role = 'standard'
      current_user.stripe_charge_ID = charge.id
      current_user.save
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Blocipedia Premium Membership - #{current_user.email}",
      amount: 15_00
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    wiki = Wiki.find(params[:wiki_id])
    user = User.find(params[:user_id])
    collaborator = user.collaborators.build(wiki: wiki)

    if collaborator.save
      flash[:notice] = "Collaborator saved"
    else
      flash[:alert] = "Unable to update collaborators."
    end

    redirect_to :back
  end

  def destroy
    wiki = Wiki.find(params[:wiki_id])
    user = User.find(params[:user_id])
    collaborator = user.collaborators.find(params[:id])

    if collaborator.destroy
      flash[:notice] = "Collaborator deleted"
    else
      flash[:alert] = "Unable to update collaborators."
    end

    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved."
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Post was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)
    options ={
      filter_html:  true,
      hard_wrap:    true,
      prettify:     true,
      space_after_headers: true,
      fenced_code:  true
    }

    extensions = {
      autolink:     true,
      superscript:  true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    syntax_highlighter(markdown.render(text)).html_safe
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  
end

app/views/charges/new.html.erb
<div class="jumbotron">
  <h1 class="text-center">Upgrading to a Premium Wiki Account</h1>
</div>
<div class="row">
  <div class="col-md-4">
    <h2 class="text-center">Private Wikis</h2>
    <p>With a Premium membership you can post private wikis.</p>
  </div>
  <div class="col-md-4">
    <h2 class="text-center">Add and delete users from you wikis.</h2>
    <p>You get control over who can contribute to your wikis</p>
  </div>
  <div class="col-md-4">
    <h2 class="text-center">One time low payment.</h2>
    <p>The best part of being a premium member is that it is only $15.00!</p>
  </div>
</div>

<div class="row">
  <div class="col-md-3 col-md-offset-5">

    <%= form_tag charges_path do %>
      <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%=@stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
    <% end %>
  </div>
</div>

app/views/collaborators/_collaborator.erb
<% if current_user.premium? %>
  <% User.all.each do |user| %>
    <div class="user">
      <% if collaborator = user.collaborator_for(wiki) %>
        <%= link_to [wiki, user, collaborator], class: 'btn btn-danger', method: :delete do %>
          <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Remove <%= user.email %>
        <% end %>
      <% else %>
        <%= link_to [wiki, user, Collaborator.new], class: 'btn btn-primary', method: :post do %>
          <i class="glyphicon glyphicon-star"> </i>&nbsp; Add <%= user.email %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>

      <div class="pull-right user-info">
      <% if current_user %>
        <div class="pull-right">
          <%= link_to "Sign Out", destroy_user_session_path(current_user), method: :delete %>
        </div>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type+"button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/refunds/new.html.erb
<h1>We will miss you! If your sure you do not wish to be a premium member anymore please click the button below</h1>
<%= @refund.submit "Save", class: 'btn btn-success' %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="row">
  <h1 class="text-center">Blocipedia: Social, Markdown Wikis</h1>
</div>

<div class="text-center">
  <div class="jumbotron">
      <h1><small>Create and share Markdown Wikis</small></h1>
      <p>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
      </p>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h3>Create as many public wikis as you want!</h3>
    </div>
    <div class="col-md-6">
      <h3>Create private wikis!</h3>
      <%= link_to "Premium Plan", new_charge_path %>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="row">
  <div class="col-md-8">
    <p>Some tips if you want to use markdown:</p>
    <ul>
      <li>Use three back ticks before and after your code to create a code block. (```code```)</li>
      <li>To bold something use two astricks before and after your text (**text to bold**)</li>
      <li>To create block quotes insert a '>' before your text </li>
    </ul>
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <p>Collaborators</p>
    <%= render partial: 'collaborators/collaborator', locals: {wiki: @wiki} %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Wikis</h1>
  </div>
  <div class="col-md-6">
  <div class="pull-right">
    <% if current_user %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>
</div>
<% @wikis.each do |wiki| %>
  <h4>
    <table class="table table-hover">
      <tr>
        <% if !wiki.private || current_user.premium? || current_user.admin? %>
          <td><%= link_to wiki.title, wiki %></td>
        <td>
          <div class="pull-right">
            <% if current_user %>
            <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-success' %>
            <%= link_to "Delete Wiki", wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
          </div>
        <% end %>
        </td>
        <% end %>
      </tr>
    </table>
  </h4>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
  <div class="row"></div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>